- src/jsTypeFactory.cc
This pull request resolves the following internal ticket: https://distributive.atlassian.net/browse/BF2-42
> BF-42: UCS4-range strings do not work properly when passed as arguments to JS-defined functions

- tests/python/test_pythonmonkey_eval.py
JS `Date()` constructor interprets `year` values from `0` to `99` as the years `1900` to `1999`
---
This pull request resolves the following internal ticket:
* https://distributive.atlassian.net/browse/BF2-51
> BF-51: js Date does not equal to py datetime in tests if the year number is less than 100

- LICENSE
PythonMonkey is licensed under the [MIT License](https://opensource.org/license/mit/). We need a `LICENSE` file to indicate that.
This pull request resolves the following internal ticket: https://distributive.atlassian.net/browse/BF2-53
> BF-53: Add license file

- .github/workflows/tests.yaml
- setup.sh
https://github.com/Distributive-Network/PythonMonkey/actions/runs/5084218550/jobs/9136227002#step:6:1102
---
https://docs.python.org/3/whatsnew/3.11.html#porting-to-python-3-11
> [open()](https://docs.python.org/3/library/functions.html#open), [io.open()](https://docs.python.org/3/library/io.html#io.open), [codecs.open()](https://docs.python.org/3/library/codecs.html#codecs.open) and [fileinput.FileInput](https://docs.python.org/3/library/fileinput.html#fileinput.FileInput) no longer accept 'U' (“universal newline”) in the file mode. In Python 3, “universal newline” mode is used by default whenever a file is opened in text mode, and the 'U' flag has been deprecated since Python 3.3. The [newline parameter](https://docs.python.org/3/library/functions.html#open-newline-parameter) to these …
> Fix/spidermonkey-build: SpiderMonkey build system breaks on Python 3.11

- .github/workflows/test-and-publish.yaml
https://github.com/Distributive-Network/PythonMonkey/actions/runs/5115473014/jobs/9196841495?pr=24#step:8:18 fails because cmake is not using the correct version of Python to build `pythonmonkey.so`.
> CI: build using the correct Python version

- .github/workflows/test-and-publish.yaml
This would allow us to test the CI-built package locally, for any branch/commit.
> CI: upload wheel as CI artifacts

- src/jsTypeFactory.cc
- tests/python/test_pythonmonkey_eval.py
Before the patch
```py
def ident(x):
print(x()) # 123.0
return x
a = pm.eval("""(py_fn) => {
const fn = py_fn(()=>{ return 123 })
fn instanceof Function // true
fn() // ??? TypeError: fn is not a function
return fn
}""")(ident)
print(a()) #segfault
```
After patch
---
This pull request resolves the following internal ticket:
* https://distributive.atlassian.net/browse/BF2-60
> BF-60: JS function corrupts after round-trip back from a Python function

- src/IntType.cc
- src/setSpiderMonkeyException.cc
Although not mentioned anywhere in Python 3.12 changelog, the internal representation of the sign bits and number of digits for a Python int has been changed in Python 3.12.
Comparing https://github.com/python/cpython/blob/v3.12.0b1/Include/cpython/longintrepr.h#L82-L90 and https://github.com/python/cpython/blob/v3.11.3/Include/cpython/longintrepr.h#L82-L85, `PyLongObject` is no longer an extension of the `PyVarObject` struct, thus the sign bit is no longer the sign of `obj->ob_size`.
Instead, this info is stored in `obj->long_value.lv_tag`, using lower 2 bits for sign, 1 bit reserved, and the remaining for the digit count.
https://github.com/python/cpython/blob/v3.12.0b1/Include/internal/pycore_long.h#L111-L115
> Fix: python 3.12 bigint

- tests/python/test_pythonmonkey_eval.py
https://github.com/Distributive-Network/PythonMonkey/actions/runs/5339271775/jobs/9677770176?pr=43#step:9:43
Tests may fail because of `ValueError: microsecond must be in 0..999999`
In `datetime.replace` the `microsecond` argument must be in the range of 0..999999, but in our case it would be rounded to 1000000 if >= 999500
> Fix tests of `eval_dates`

- CMakeLists.txt
- src/CMakeLists.txt
Previously we set multiple conflicting `CXX_STANDARD` values in different places.
> chore: build with C++20 standard consistently

- include/PyEventLoop.hh
https://github.com/Distributive-Network/PythonMonkey/actions/runs/5359371052/jobs/9722883376#step:7:250
```
error : incomplete type 'PyEventLoop::AsyncHandle' used in type trait expression
```
C++20 is more strict on that
> Fix Windows build on C++ 20 standard

- .github/workflows/test-and-publish.yaml
- README.md
Implemented based on https://peps.python.org/pep-0503/
People can install nightly builds using 
```sh
pip install -i https://nightly.pythonmonkey.io/ pythonmonkey
```
> Publish nightly builds as a very basic Python package repository to GitHub Pages

- .github/workflows/test-and-publish.yaml
- poetry.lock
- pyproject.toml
https://github.com/Distributive-Network/PythonMonkey/actions/runs/5414159268/jobs/9844895604#step:5:238
> Hash for numpy (2.0.0.dev0) from archive numpy-2.0.0.dev0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl not found in known hashes (was: sha256:8a9b6d9543618a0b4aba4a29b12853042adccfc416809398121a143751c0da14)
It seems that the package content has changed for the same version `numpy-2.0.0.dev0`.
We copy the package to our own [`pythonmonkey` namespace on Anaconda](https://anaconda.org/pythonmonkey/numpy) to pin version.
> Fix numpy dep for Python 3.12

- CMakeLists.txt
The `LINUX` variable was added in cmake 3.25, and the `UNIX` variable is broad that also includes macOS
> `UNIX`: is TRUE on all UNIX-like OS's, including Apple OS X and _CygWin_
> chore: set the minimum cmake version to 3.25

- python/pythonmonkey/require.py
`python.load` should use the `module.exports` dict instead of taking the Pythonic exports
> Fix: Python modules require can't see `exports['abc'] = xyz`

- .github/workflows/test-and-publish.yaml
- setup.sh
Building SpiderMonkey is broken in our CI when cache is not hit
> fix spidermonkey build

- .github/workflows/test-and-publish.yaml
- setup.sh
We should make sure that https://ubuntu.com/security/notices/USN-6147-1 doesn't affect us before launch.
It was patched in SpiderMonkey 102.12, but we are currently building against SpiderMonkey 102.11.
> chore: upgrade SpiderMonkey to 102.13.0 ESR

- python/pminit/pminit/cli.py
- python/pminit/pyproject.toml
Added a pminit cli tool that enables developers to modify or change package.json for pythonmonkey and even force reinstallation of the node packages.
After this PR, one will be able to do:
`poetry run pminit npm install`
This feature was asked for by @wesgarland and I think it's a very useful addition.
> feature(pminit): added pminit cli tool 

- .github/workflows/test-and-publish.yaml
- README.md
- pyproject.toml
- python/pminit/pyproject.toml
* Fix installation of the nightly build 
```console
ERROR: Could not find a version that satisfies the requirement pminit (from pythonmonkey) (from versions: 0.0.1.dev938+aa27f65)
ERROR: No matching distribution found for pminit
```
* Fix installation from [source distribution](https://packaging.python.org/en/latest/specifications/source-distribution-format/)
> add `--no-binary pythonmonkey` flag to pip to not use the wheel package
```bash
ModuleNotFoundError: No module named 'poetry_dynamic_versioning.backend'
```
* Improve https://nightly.pythonmonkey.io/ UI
> Fix nightly build

- .gitignore
When I use poetry, I configure it to create the project's virtual environment in the project, rather than under the cache directory [^1]. e.g.,
```console
$ poetry config --list | grep in-project
virtualenvs.in-project = true
```
This makes it easier to have tools like `rtx` auto activate the virtual environment whenever I `cd` into the project folder [^2], skipping the need to explicitly activate the shell or use `poetry run`.
It's also a commonly ignored file in Python projects [^3].
[^1]: https://python-poetry.org/docs/configuration/#virtualenvsin-project
[^2]: https://github.com/jdxcode/rtx/blob/v1.34.0/docs/python.md#experimental-automatic-virtualenv-creationactivation
[^3]: https://github.com/github/gitignore/blob/main/Python.gitignore
> chore(git): ignore local `.venv` folder

- setup.sh
In a fresh docker container in `ubuntu:20.04`, `curl` isn't installed by default. After installing `git` and `sudo`, I ran `setup.sh` and ran into "curl: command not found".
Given that `setup.sh` uses `curl` right after `apt` installing other packages on Ubuntu machines, we may as well make sure it's available before using it.
After resolving that, Poetry failed to install due to the python module `distutils` being missing [^1]. Fixing it through installing `python3-distutils` seems to work [^2]!
After troubleshooting OS/machine specific dependency setup issues (e.g., `npm`, latest `cmake`), I had to add `python3-dev` to make `setup.sh` match what the README file mentions in the "Build Instructions" section.
[^1]: https://github.com/pypa/get-pip/issues/124
[^2]: …
> build(setup.sh): add missing pkgs on fresh ubuntu systems

- peter-jr
This should get the build working on mac without installing shell helpers that don't ship with macos. Tested on ```Darwin Wes-iMac-2019.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Apr 18 21:50:40 PDT 2022; root:xnu-6153.141.62~1/RELEASE_X86_64 x86_64
.```
> peter-jr - supply wc -L and realpath good-enough polyfills

- .gitignore
- python/pythonmonkey/builtin_modules/console.js
- tests/js/console-stdio.bash
- tests/js/console-this.simple
- tests/js/is-compilable-unit.simple
Issue 90 is because of unbound `this`
Current version of NodeJS use ownProperties for the different methods of console, and some DCP code depends on this.
I added a test to test this stuff, and it passes on node 14, as well as pmjs now.
> console.js - use own props instead of inheritance 

- peter-jr
This PR makes `.failing` tests exit with code 0 to make Peter Jr. model the same behaviour as Peter. Like father, like son.
This PR resolves issue #102.
> Bugfix: Exit with code 0 for failures with .failing tests

- tests/js/js2py/arraybuffer.simple
- tests/js/py2js/arraybuffer.simple
Add two tests to check the interoperability of the ArrayBuffer datatype. These tests check that the ArrayBuffer can be copied to python, mutated, and read back from JS. They also test that a python "Buffer" (bytearray) can be read in JS, mutated, and read back.
> Add tests for the ArrayBuffer datatype

- tests/js/js2py/promise-await-in-python.simple.failing
- tests/js/js2py/promise.simple.failing
- tests/js/py2js/promise.simple.failing
Implement testing for converting a JS Promise to a Python awaitable. Currently this functionality doesn't exist, resulting in most tests seg faulting, or running into other errors.
> Testing: add tests for passing promises between JS and Python

- build.py
Build.py was originally assuming we were at the project root for a few things, this is no longer the case and build.py makes sure to start the child processes in the right locations.
> fix(build.py): build.py doesn't assume location

- README.md
- pmjs
- python/pythonmonkey/require.py
- src/modules/pythonmonkey/pythonmonkey.cc
- tests/js/pmjs-eopt.bash
This fixes
- problems displaying object literals in the repl (now same as node)
- problems using boolean options in pm.eval
- segfault when pm.eval is called with no arguments
> pmjs improved parsing

- .github/ISSUE_TEMPLATE/bug_pythonmonkey.yaml
- .github/ISSUE_TEMPLATE/feature_pythonmonkey.yaml
This PR adds two templates to the PythonMonkey repository. One for feature requests and one for bug reports.
The bug report template was heavily inspired by and partially copied from [Tensorflow's `TensorFlow Issue Template` template](https://github.com/tensorflow/tensorflow/issues/new/choose).
---
You can view the proposed bug report and feature request issues here: [https://github.com/wiwichips/PythonMonkey/issues/new/choose](https://github.com/wiwichips/PythonMonkey/issues/new/choose). Feel free to test them out and see what they look like!
Here are screenshots:
> Add templates for GitHub issues

- include/pyTypeFactory.hh
- src/jsTypeFactory.cc
- src/pyTypeFactory.cc
- tests/python/test_pythonmonkey_eval.py
Closes https://github.com/Distributive-Network/PythonMonkey/issues/65, https://github.com/Distributive-Network/PythonMonkey/pull/19
Possibly related to https://github.com/Distributive-Network/PythonMonkey/issues/112
Return the underlying function in its original language rather than wrapping it again.
> unwrap functions when returned to their original language

- include/StrType.hh
- include/modules/pythonmonkey/pythonmonkey.hh
- python/pythonmonkey/pythonmonkey.pyi
- src/StrType.cc
- src/modules/pythonmonkey/pythonmonkey.cc
- tests/python/test_pythonmonkey_eval.py
- tests/python/test_strings.py
Fixes https://github.com/Distributive-Network/PythonMonkey/issues/89
* Convert strings that require conversion to UCS4 automatically to avoid surprises.
* Remove `pm.asUCS4` method as encoding conversion is done automatically
> Fix non-BMP strings

- .github/workflows/test-and-publish.yaml
- poetry.lock
- pyproject.toml
- python/pythonmonkey/cli/pmjs.py
- python/pythonmonkey/require.py
- tests/js/commonjs-modules.bash
- tests/js/console-stdio.bash
- tests/js/pmjs-eopt.bash
- tests/js/pmjs-global-arguments.bash
- tests/js/pmjs-interactive-smoke.bash
- tests/js/pmjs-popt.bash
- tests/js/pmjs-require-cache.bash
- tests/js/pmjs-ropt.bash
- tests/js/typeofs.simple
Closes https://github.com/Distributive-Network/PythonMonkey/issues/111
> Make pmjs & peter-jr work on Windows

- python/pythonmonkey/require.py
In Google Colab
```
!pip install pythonmonkey
```
```py
import pythonmonkey as pm
```
```console
/usr/local/lib/python3.10/dist-packages/pythonmonkey/require.py in <module>
47 # Windows may use other encodings / code pages that have many characters missing/unrepresentable
48 # Error: Python UnicodeEncodeError: 'charmap' codec can't encode characters in position xx-xx: character maps to <undefined>
---> 49 sys.stdout.reconfigure(encoding='utf-8')
50 sys.stderr.reconfigure(encoding='utf-8')
51 
AttributeError: 'OutStream' object has no attribute 'reconfigure'
```
> fix: stdio stream objects may be monkeypatched at runtime not being instances of TextIOWrapper

- python/pythonmonkey/__init__.py
- python/pythonmonkey/helpers.py
- python/pythonmonkey/require.py
- basically everything in an "empty" global (like Array, WebAssembly, Uint8Array, escape, Date, etc) is now an export of pythonmonkey
- new and typeof operators are wrapped in functions for pythonic use
```
>>> import pythonmonkey as pm
>>> a=pm.new(pm.Uint8Array)([3,4,5])
>>> a
<memory at 0x7fe4415e93c0>
```
> A pm.new and other helpers

- README.md
- python/pythonmonkey/cli/pmjs.py
- python/pythonmonkey/lib/pmdb.py
- src/JobQueue.cc
- src/modules/pythonmonkey/pythonmonkey.cc
Automatically enter the debugger on `debugger;` statements and uncaught exceptions
Supported commands:
- `b <lineNumber>`/`break <lineNumber>`: Set breakpoint on specific line
- `c`/`cont`: Continue execution until next breakpoint or `debugger` statement
- `n`/`next`: Step next
- `bt`/`backtrace`: Print backtrace of current execution frame
- `l`/`line`: Print current line
- `p <expr>`/`print <expr>`/`exec <expr>`: Execute an expression in debugging script's context and print its value
- `q`/`quit`/`kill`: Force exit the program
- `h`/`help`: Print help message
---
In pmjs, pmdb can be enabled by the `--inspect` flag
```bash
$ poetry run pmjs --inspect ddd.js
```
```js
// ddd.js
function abc() {
let i = 0;
let j = 1;
debugger;
i = 2; j = 2;
i++
}
abc(1, 3, 5)
```
```console
(pmdb) > bt …
```
> Feat: pmdb, a gdb-like JavaScript debugger interface

- python/pminit/post-install-hook.py
This change prints an error message during pip install when npm is not installed on the system:
The error should show up like this:
```
Building wheels for collected packages: pminit
Building wheel for pminit (pyproject.toml) ... error
error: subprocess-exited-with-error
× Building wheel for pminit (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [38 lines of output]
PythonMonkey Build Error:
*    It appears npm is not installed on this system.
*    npm is required for PythonMonkey to build.
*    Please install NPM and Node.js before installing PythonMonkey.
*    Refer to the documentation for installing NPM and Node.js here: https://nodejs.org/en/download
Traceback (most recent call last):
File "/tmp/pip-req-build-ryy_b0um/post-install-hook.py", line 38, in <module>
main() …
```
> Add actionable error message for no npm on system during pip install

- tests/js/js2py/error.simple
- tests/js/py2js/error.simple
Added the Error object conversion test.
Note that the custom properties on these errors are not preserved in either case. 
This behaviour is currently intended but may be subject to change in the future, thereby, these tests should be updated to test that behaviour accordingly.
> feature(tests): add js py2js and js2py error conversion test

- include/PyProxyHandler.hh
- src/PyProxyHandler.cc
`Object.values`/`Object.entries` requires calling the `getOwnPropertyDescriptor` method on a Proxy object.
See https://hg.mozilla.org/releases/mozilla-esr102/file/381b375/js/src/builtin/Object.cpp#l1829
This pull request would fix https://github.com/Distributive-Network/PythonMonkey/issues/117 and fix https://github.com/Distributive-Network/PythonMonkey/issues/91
> Fix `Object.values`/`Object.entries`/`JSON.stringify` on python dicts

- .github/workflows/test-and-publish.yaml
`poetry publish` can only publish the packages with the same version number defined in `pyproject.toml` (version `0` without poetry-dynamic-versioning)
Also it cannot upload the `pmint` packages.
We should just switch to `twine upload dist/*` that uploads everything under the `dist` directory.
> CI: fix PyPI publishing

- .github/workflows/test-and-publish.yaml
- setup.sh
`setup.sh` may fail on the first run because the `poetry` command may not available immediately after installation
> fix: poetry-dynamic-versioning installation

- build.py
- tests/js/commonjs-modules.bash
To test this, add `--no-binary pythonmonkey` flag to `pip install` to forcibly install from source code.
> fix(build.py): `git submodule update` fails when installing from source distribution (sdist)

- include/JSObjectProxy.hh
- src/JSObjectProxy.cc
- src/modules/pythonmonkey/pythonmonkey.cc
- tests/python/test_dicts_lists.py
now support the "in" operation for Dicts
cleanup unused method
fix memory leak
closes #187 
Does not implement "in" for Lists yet. This is left to https://github.com/Distributive-Network/PythonMonkey/pull/186
> "contains" method for Object "in" operations added

- .github/workflows/test-and-publish.yaml
We currently always install the latest MozillaBuild version from https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe. 
On [11-Jan-2024](https://ftp.mozilla.org/pub/mozilla/libraries/win32/), MozillaBuild version 4.1 was [released](https://groups.google.com/u/1/a/mozilla.org/g/dev-platform/c/hF51Q3j6ca8), and it contained some [behaviour changes](https://bugzilla.mozilla.org/show_bug.cgi?id=1869958) that we didn't know. 
This PR adds an env var to preserve MozillaBuild v4.0.x behaviour.
See https://groups.google.com/u/1/a/mozilla.org/g/dev-platform/c/hF51Q3j6ca8,
also https://bugzilla.mozilla.org/show_bug.cgi?id=1869958
> ci: fix MozillaBuild

- .github/workflows/test-and-publish.yaml
- build.py
- src/PyDictProxyHandler.cc
- src/PyListProxyHandler.cc
Current resolution for attempting to get rid of the Proxies's PyObject reference: not needed since we are only freed when the process exits.
Allow building with any python version set up by pyenv
sync git action spidermonkey version with setup.sh
> TODOS for improved memory management and minor improvements

- src/PyDictProxyHandler.cc
- src/PyListProxyHandler.cc
- src/jsTypeFactory.cc
Proxy finalize only calls Py_DecRef on the proxied object if we are not shutting down: there is only reference left at shutdown and it will go away with the process space so there is no need to decref it
closes https://github.com/Distributive-Network/PythonMonkey/issues/220
> finalizing proxies: do not decref when shutting down

- python/pythonmonkey/builtin_modules/XMLHttpRequest.js
- python/pythonmonkey/builtin_modules/timers.js
- src/internalBinding/timers.cc
- tests/python/test_event_loop.py
This PR fixes the following issues:
* In XMLHttpRequest, previously we throw a `DOMException(InvalidAccessError)` when trying to access the `xhr.withCredentials` getter/setter. However in socket.io-client, it tries to set `xhr.withCredentials` but cannot catch the exception, thus breaks the connection.
* In our `clearTimeout` API, previously we expects the [`timeoutId` argument](https://developer.mozilla.org/en-US/docs/Web/API/clearTimeout#parameters) is stored as an int32 value internally (JS numbers are always float64 values **in JS context** but mostly they are optimized **internally**). However in practice, JS number is not always optimized to an int32 value even though it's integral. 
In socket.io, old timers for the connection `timeout` don't get cancelled properly because the …
> Fix Socket.IO connection timeout

- tests/python/test_event_loop.py
The test for https://github.com/Distributive-Network/PythonMonkey/blob/59b2fadf6eccd0439ec38946cb7fd045cd5d491e/tests/python/test_event_loop.py#L49 [initially succeeded](https://github.com/Distributive-Network/PythonMonkey/actions/runs/7932630581/job/21661171813) but sometimes [fails](https://github.com/Distributive-Network/PythonMonkey/actions/runs/7934694415/job/21667006073) because the machine running too slow (maybe).
> Hotfix: Loosen tests timeout

- .github/workflows/test-and-publish.yaml
Instead of using our own m2 machine in the office,
move to the GitHub hosted workers as they have apple silicon (m1) runners now.
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
> CI: use GitHub hosted runners to build for arm64 macOS

- build.py
`-DPYTHON_INCLUDE_DIR=` or `-DPYTHON_LIBRARY=` are no longer needed since we have https://github.com/Distributive-Network/PythonMonkey/blob/1fcd5e4/CMakeLists.txt#L61-L63 in cmakelists. 
CMake should already be able to use the python version managed by a virtual environment with `Python_FIND_VIRTUALENV` set to `FIRST`
https://cmake.org/cmake/help/latest/module/FindPython.html
> Chore: remove the redundant python location lookup in `build.py`

- src/modules/pythonmonkey/pythonmonkey.cc
- tests/python/test_pythonmonkey_eval.py
Parsing of options given to pm.eval now works for both JS and Python options types 
closes https://github.com/Distributive-Network/PythonMonkey/issues/258
closes https://github.com/Distributive-Network/PythonMonkey/issues/259
> evalOptions now work for both JSObjectProxy and Dict

- src/modules/pythonmonkey/pythonmonkey.cc
- tests/js/eval-test.simple
- tests/js/resources/eval-test.js
Now we can pass a python file as the first arg to pm.eval.  The JSAPI code assumes the file is in UTF-8 and does not blow it up to char16_t before compilation.
This means that we don't need to load the giant dcp-client bundle into memory and convert from utf8 to ucs2 before execution just to throw it all away a few lines later.
> pm.eval - support open file as first arg, issue 230

- peter-jr
- python/pythonmonkey/cli/pmjs.py
There have been some pmjs regressions over the last year
- .python command is broken
-  sigint no longer aborts peter-jr
Update: sigint problem was actually peter-jr, not pmjs
both problems fixed in this PR
> pmjs - fix .python command, peter-jr - fix sigint

- python/pythonmonkey/cli/pmjs.py
- python/pythonmonkey/require.py
- tests/js/set-timeout.simple
- can now use timers inside pmjs REPL, although they can only fire after you press enter
- there is now a set timeout test
- this test required my to add process.exit.code feature to require.py so that we didn't have false positives when the timer just never fired
> pmjs timeout improvements

- python/pythonmonkey/builtin_modules/util.js
- tests/js/util-module.simple
The `util.format` code [looks up all its own enumerable properties](https://github.com/Distributive-Network/PythonMonkey/blob/4901d0b/python/pythonmonkey/builtin_modules/util.js#L443) by `Object.keys()` then prints them out.
In SpiderMonkey, when changing the `stack` property of an `Error` object, `stack` becomes an enumerable property, while V8 doesn't. Our `util.inspect`/`util.format` code was copied from Node.js, so it won't handle the difference.
According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack#value, the `stack` property is implementation dependent.
> Fix(console): extra stack property is printed after the stack trace

- include/setSpiderMonkeyException.hh
- src/ExceptionType.cc
- src/jsTypeFactory.cc
- src/setSpiderMonkeyException.cc
- tests/python/test_arrays.py
Addendum to https://github.com/Distributive-Network/PythonMonkey/pull/286
Provide Full JS context when catch a Python Exception happening in a JS context
> Python Trace supplement: Full JS stack trace details

- include/PyEventLoop.hh
- python/pythonmonkey/builtin_modules/internal-binding.d.ts
- python/pythonmonkey/builtin_modules/timers.js
- src/PyEventLoop.cc
- src/internalBinding/timers.cc
- tests/python/test_event_loop.py
* implement Node.js-style `Timeout` class (It can be [coerced](https://github.com/Distributive-Network/PythonMonkey/pull/294/files#diff-ca51878c52f36c3c60817c6985d3b4db4201d2f29b04a986b928baeb76419354R29-R35) into a pure `number` by `+timeoutId` or `Number(timeoutId)`.)
* implement [timers `.ref()`/`.unref()` functions](https://nodejs.org/api/timers.html#timeouthasref)
> Feat: Node.js-style timers

- .vscode/launch.json
- .vscode/tasks.json
This PR changes the VSCode visual debugger's `preLaunchTask` to only run `build.py`.
This avoids wasting time by trying to update dependencies by `poetry install`.
> VSCode Debugger Fast Build

- src/JobQueue.cc
- src/PyEventLoop.cc
- src/internalBinding/utils.cc
- tests/python/test_event_loop.py
```js
setInterval(()=>console.log(123), 200).unref()
setTimeout(()=>console.log(5), 500)
```
It should stop after 500ms
> HOTFIX: `.unref()` not working on `setInterval` timers

- python/pythonmonkey/builtin_modules/XMLHttpRequest-internal.py
GC issues now resolved so can inline the call parameters
> Can now inline call params to processResponse

- .github/workflows/test-and-publish.yaml
This PR fixes a bug introduced by #322 that broke uploading docs by CI during the `publish-nightly` step on main
> fix(CI): correctly upload docs from the runner that builds them

- poetry.lock
- pyproject.toml
This PR updates the minimum required version of pminit to 0.4.0, so that when users upgrade their installation of pythonmonkey with `pip install pythonmonkey --upgrade`, core-js will be available even if the user has an old version of pminit that pre-dates our inclusion of core-js.
addresses #185 once we publish a new release
> chore(meta): update minimum pminit version in poetry.lock

- src/internalBinding/timers.cc
- tests/python/test_event_loop.py
We were only calling `removeRef` after the timer's job function is run. https://github.com/Distributive-Network/PythonMonkey/blob/08b923c08752bed58d94f9d6bf84dae08cc7d093/src/PyEventLoop.cc#L54
However, when a interval timer gets cancelled between its runs, the job function won't run, thus the timer won't be automatically unref'ed.
> HOTFIX: `clearInterval` won't unref the timer sometimes

- .vscode/tasks.json
The `Fast Build` task should build in Debug as it's supposed to run from the VSCode visual debugger.
> Change the build task for VSCode to build in Debug mode

- .github/workflows/test-and-publish.yaml
GitHub limits the number of concurrent macOS runners to 5. 
macOS 13 CI runs here are redundant since our binary files built for macos-12 are forward-compatible on macos-13.
I was putting both macos-12 and macos-14 tags here just in order to build on both amd64 and arm64 (macos-14 exclusively) architectures than to differentiate the OS versions. https://github.com/Distributive-Network/PythonMonkey/commit/c402def
> CI: remove redundant macOS 13 CI runs to save the limit of concurrent macOS CI jobs

- cmake/docs/Doxyfile.in
JavaScript is actually supported by Doxygen
In https://www.doxygen.nl/manual/config.html `EXTENSION_MAPPING`
> ... language is one of the parsers supported by doxygen: IDL, Java, JavaScript, Csharp (C#), C, C++, Lex, D, PHP, md (Markdown), Objective-C, Python, Slice, VHDL, Fortran
And I could verify it working by looking at the generated `Class List` page.
This reverts commit ea30c367c7ca5b5bee39905ad091275acff18354 "chore(docs): JavaScript is not support by Doxygen".
Actually I added JavaScript on purpose in commit c89a67fc50788799833f299362e3000df4822b84.
> Add back JavaScript files to Doxygen-generated docs

- .github/workflows/test-and-publish.yaml
Shipping more binary files would save us from some users complaining unable to build/install.
> Build binary files that support Python 3.8 for amd64 macOS

- setup.sh
When installing within a Docker container, the user in use may be `root` and `sudo` might not be installed. This patch allows pythonmonkey to be installed in a Docker container without having to install `sudo` first
> When running as root, skip sudo in setup script

- Makefile
- include/JSStringProxy.hh
- include/StrType.hh
- include/jsTypeFactory.hh
- src/ExceptionType.cc
- src/JSObjectIterProxy.cc
- src/JSStringProxy.cc
- src/StrType.cc
- src/jsTypeFactory.cc
- src/modules/pythonmonkey/pythonmonkey.cc
- src/pyTypeFactory.cc
- src/setSpiderMonkeyException.cc
- tests/python/test_strings.py
This PR fixes #293, an issue where strings returned by `eval` were rooted for the entire lifetime of the program, rather than only for the lifetime of the underlying PyUnicodeObject.
This PR also fixes #299, an issue where JSExternalStrings passed back to python would create a new PyUnicodeObject using the same underlying char buffer, rather than the exact same PyUnicodeObject.
> JSString Improvements

- python/pythonmonkey/builtin_modules/console.js
- tests/js/console-methods.simple
Console.trace's own context should not be printed in the output but it is now:
With 
import pythonmonkey as pm
pm.eval('function foo(){ function bar() { console.trace() } bar(); } foo();')
get
Trace
_home_philippe_Sources_PythonMonkey_python_pythonmonkey_builtin_modules_console_js/Console/this.trace@/home/philippe/Sources/PythonMonkey/python/pythonmonkey/builtin_modules/console.js:104:22
bar@evaluate:1:42
foo@evaluate:1:52
@evaluate:1:61
Now fixed to 
import pythonmonkey as pm
pm.eval('function foo(){ function bar() { console.trace() } bar(); } foo();')
gets
Trace
bar@evaluate:1:42
foo@evaluate:1:52
@evaluate:1:61
> Do not print the internal implementation line in the console trace method

- python/pythonmonkey/pythonmonkey.pyi
For https://github.com/Distributive-Network/PythonMonkey/pull/364/commits/f1f324162cf1ae3e7cf79d29964e2e9892524733, I have absolutely no idea why the type definitions were deleted by @philippedistributive in commit https://github.com/Distributive-Network/PythonMonkey/commit/d946421c2ef75e10f7c7f527f0d473bb087b3cde and https://github.com/Distributive-Network/PythonMonkey/commit/1f42778740b89e8f6947b13b2c6b4c80267f298c. 
`pm.bigint` is very useful when losslessly converting a Python `int` into JS and back (see https://github.com/Distributive-Network/PythonMonkey?tab=readme-ov-file#integer-type-coercion), thus must be included in the typings for the public API.
> Add more type hints & documentations for the public API in the `.pyi` stub file

- python/pminit/pminit/cli.py
closes https://github.com/Distributive-Network/PythonMonkey/issues/254
> `pminit` should exit directly once the `npm` command it runs ends with a non-zero exit code

- README.md
- python/pythonmonkey/require.py
- src/pyTypeFactory.cc
If the last expression value is a JS type that can't currently be converted to a Python type in PythonMonkey 
(e.g. JS [`Symbol`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) type), 
`pmjs` should ignore it completely instead of trying to covert it so hard (segfault/error).
> PMJS should run files in script mode, shouldn't try to retrieve the last expression value of the file

- python/pythonmonkey/helpers.py
- src/JobQueue.cc
- tests/js/uncaught-rejection-handler.bash
When not in the `pmjs` environment, uncaught JS Promise rejections would give a Python `Future exception was never retrieved` error message after https://github.com/Distributive-Network/PythonMonkey/pull/156 has been merged.
This PR would make it print out the actual JS error just like what it does in pmjs. 
---
closes https://github.com/Distributive-Network/PythonMonkey/issues/357
> Fix the `Future exception not retrieved` issue

- src/jsTypeFactory.cc
- tests/python/test_arrays.py
- tests/python/test_functions.py
This PR fixes #265, by allowing JS code to call python functions even when supplied too many or too few arguments. 
When too many arguments are supplied, those beyond the function's argument count are ignored, e.g.:
```py
def f(a, b):
return [a, b]
assert [1, 2] == pm.eval("(f) => f(1, 2, 3)")(f)
```
When too few arguments are supplied, those beyond the number of supplied arguments are passed as `None` to match JavaScript's behaviour of passing `undefined`, e.g.:
```py
def f(a, b):
return [a, b]
assert [1, None] == pm.eval("(f) => f(1)")(f)
```
This also works for functions with default arguments, or varargs, e.g.:
```py
def f(a, b, c=42, d=43, *args):
return [a, b, c, d, *args]
assert pm.eval("(f) => f(1, 2, 3, 4, 5)")(f) == [1, 2, 3, 4, 5] 
assert pm.eval("(f) => f(1, 2, 3, 4)")(f) == …
```
> fix python function arg-count mismatch frustration

- .gitignore
- setup.sh
https://github.com/Distributive-Network/PythonMonkey/actions/runs/9576344507/job/26402698600#step:6:5197
SpiderMonkey build fails on Windows when building uncrustify (on `main` branch)
```console
make: *** No targets specified and no makefile found.  Stop.
```
---
It seems to be a long existing issue, probably since https://github.com/Distributive-Network/PythonMonkey/pull/322 changed how `uncrustify` is built.
However, we haven't run any full SpiderMonkey build (we're always using the build cache) in the past 2 months since the PR was merged, so the issue hasn't been surfaced until recently... :sweat_smile:
> Chore(CI): fix building `uncrustify` on Windows

- src/JSArrayProxy.cc
- src/JSObjectProxy.cc
Handle NULL result from pyTypeFactory and clear any exception
Take into account the proxy's jsObject address for detecting cycles
closes https://github.com/Distributive-Network/PythonMonkey/issues/379
> Properly print/repr Promises/Futures and structural cycles at the JS level

- src/PyIterableProxyHandler.cc
- src/PyObjectProxyHandler.cc
- tests/python/test_objects.py
Added constructor and Symbol.toPrimitive properties to Iterable proxy as required by console.log
closes https://github.com/Distributive-Network/PythonMonkey/issues/390
closes https://github.com/Distributive-Network/PythonMonkey/issues/388
> Support console printing of iterable proxy

- src/PyIterableProxyHandler.cc
- tests/python/test_objects.py
- tests/python/test_pythonmonkey_eval.py
Call PyObject_GetAttr instead of PyDict_GetItemWithError in iterable proxy
closes https://github.com/Distributive-Network/PythonMonkey/issues/389
> PyObject is not necessarily a dict in Iterable proxy when getting an attribute

- include/PyBaseProxyHandler.hh
- include/PyBytesProxyHandler.hh
- src/BufferType.cc
- src/PyBytesProxyHandler.cc
- src/PyObjectProxyHandler.cc
- src/pyTypeFactory.cc
- tests/python/test_buffer_typed_array.py
Added JS proxy for Python immutable bytes object
closes https://github.com/Distributive-Network/PythonMonkey/issues/385
> Introducing proxy for python bytes

- include/PyIterableProxyHandler.hh
- include/PyObjectProxyHandler.hh
- src/PyIterableProxyHandler.cc
- src/PyListProxyHandler.cc
- src/PyObjectProxyHandler.cc
- tests/python/test_objects.py
Object types such as Dict now use the Object.prototype defaults for toString, toLocaleString and valueOf
closes https://github.com/Distributive-Network/PythonMonkey/issues/396
> Objects now use prototype defaults

- src/internalBinding/timers.cc
Prevent inconsistent state crashing by exiting next operation called from JS early when system exit is under way
closes https://github.com/Distributive-Network/PythonMonkey/issues/387
> check for SystemExit before scheduling timer

- setup.sh
PR https://github.com/Distributive-Network/PythonMonkey/pull/386 tried to make the `cargo` executable immediately available in the current shell by sourcing `$HOME/.cargo/env`.
> console messages when cargo is installed by `rustup` on *nix
```console
Rust is installed now. Great!
To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).
To configure your current shell, you need to source
the corresponding env file under $HOME/.cargo.
This is usually done by running one of the following (note the leading DOT):
. "$HOME/.cargo/env"            # For sh/bash/zsh/ash/dash/pdksh
source "$HOME/.cargo/env.fish"  # For fish
```
However, this method does not work in Windows, and thus breaks our …
> Fix Windows build for finding the `cargo` executable

- .github/workflows/test-and-publish.yaml
Binaries built on Ubuntu 20.04 (uses glibc version 2.31) can run on Ubuntu 24.04 (glibc version 2.38) without any problem, but not the other way around.
We should only build on the lowest OS version possible.
CI on Ubuntu 20.04 [sometimes](https://github.com/Distributive-Network/PythonMonkey/actions/runs/10457908558/job/28963201132#step:15:154) [fails](https://github.com/Distributive-Network/PythonMonkey/actions/runs/10457594637/job/28957705334#step:15:754) because it somehow tries to pick up the binaries built for Ubuntu 24.04 (needs glibc version 2.38), which is incompatible with Ubuntu 20.04 (only has glibc version 2.31).
---
The issue https://github.com/Distributive-Network/PythonMonkey/issues/356 reported for having trouble on Ubuntu 24.04 has nothing to do with building/compiling on …
> chore(CI): remove CI runs on Ubuntu 24.04

- python/pythonmonkey/builtin_modules/base64.py
Update python implementation of 'atob' to properly reflect behaviour of JS 'atob' by padding the base64 with "==".
https://stackoverflow.com/questions/2941995/python-ignore-incorrect-padding-error-when-base64-decoding
This fixes a number of JavaScript implementations for different Cryptography logic which takes advantage of `atob`s behavior, much of this logic doesn't take into account the padding, however Python's base64 library does.
Since padding is arbitrary we can append "==" to the string before decoding.
`aGVsbG8gd29ybGQ` -> raises `binascii.Error`
`aGVsbG8gd29ybGQ=` -> `hello world`
`aGVsbG8gd29ybGQ==` -> `hello world`
`aGVsbG8gd29ybGQ===` -> `hello world`
and so on...
```py 
import base64
data = "aGVsbG8gd29ybGQ"
base64.standard_b64decode(data)
```
`binascii.Error: Incorrect …
> fix: base64.py 'Incorrect padding' error

- .github/workflows/test-and-publish.yaml
`actions/setup-python` now added prebuilt Python 3.8 & 3.9 packages for arm64 macOS.
See https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```json
{
"version": "3.8.10",
"stable": true,
"release_url": "https://github.com/actions/python-versions/releases/tag/3.8.10-8879978422",
"files": [
{
"filename": "python-3.8.10-darwin-arm64.tar.gz",
"arch": "arm64",
"platform": "darwin",
"download_url": "https://github.com/actions/python-versions/releases/download/3.8.10-8879978422/python-3.8.10-darwin-arm64.tar.gz"
},
...
```
```json
{
"version": "3.9.13",
"stable": true,
"release_url": "https://github.com/actions/python-versions/releases/tag/3.9.13-8879985561",
"files": [
{
"filename": "python-3.9.13-darwin-arm64.tar.gz",
"arch": "arm64",
"platform": "darwin", …
```
> CI: add Python 3.8 & 3.9 builds on arm64 macOS

- .github/workflows/update-mozcentral-version.yaml
Small changes on the `mozilla-central` updater CI that was introduced in https://github.com/Distributive-Network/PythonMonkey/pull/367 https://github.com/Distributive-Network/PythonMonkey/commit/a7b92e896ff6b077f161b9ae79a9f5e55f4434b5
* Fix the problem where the CI commit [always says](https://github.com/Distributive-Network/PythonMonkey/pull/416/commits/914ec9be46467069f8fdf9443b56fe6964b4aa0b) @philippedistributive to be the author 
* Automatically assign @Xmader to the PRs
* Lower the update frequency since we don't have enough bandwidth
> Small changes on the `mozilla-central` updater CI

- src/modules/pythonmonkey/pythonmonkey.cc
Set GC max heap size to maximum available to avoid OOM errors
This is done routinely in Spidermonkey (see for example https://searchfox.org/mozilla-central/rev/e968519d806b140c402c3b3932cd5f6cd7cc42ac/js/src/shell/js.cpp#13452)
See also https://discourse.mozilla.org/t/how-does-spidermonkey-deal-with-memory-limitations/123670/2
> set max gc heap size to maximum available

- src/PyObjectProxyHandler.cc
- src/modules/pythonmonkey/pythonmonkey.cc
String buffers memory would be moved around during a **minor GC (nursery collection)**.
The string buffer pointer obtained by `JS::Get{Latin1,TwoByte}LinearStringChars` remains valid only as long as no GC happens.
Even though `JS::PersistentRootedValue` does keep the string buffer from being garbage-collected, it does not guarantee the buffer would not be moved elsewhere during a GC, and so invalidates the string buffer pointer.
---
The direction of @caleb-distributive's fix in PR https://github.com/Distributive-Network/PythonMonkey/pull/417 is correct.
> Finally, it adds a GC callback that re-points all of the JSStringProxy data pointers to their associated data, since they may have moved during a GC.
However, from my testing, moving string buffers only happens during **nursery …
> Fix the string corruption bug

- src/PyBytesProxyHandler.cc
Fix recently introduced build warning
closes https://github.com/Distributive-Network/PythonMonkey/issues/426
> snprintf warning fix

- src/JSObjectProxy.cc
- tests/python/test_dict_methods.py
Do detect pending exception, report it, and issue appropriate wrapper exception at the python level 
closes https://github.com/Distributive-Network/PythonMonkey/issues/435
> Detect exception in iterator next call and StopIteration

- src/jsTypeFactory.cc
- tests/python/test_functions_this.py
Do check if method has 0 args meaning no self and ultimately fail in the correct manner
closes https://github.com/Distributive-Network/PythonMonkey/issues/436
> Fix method python method call without self

- include/StrType.hh
- python/pythonmonkey/require.py
- src/ExceptionType.cc
- src/JSObjectProxy.cc
- src/JobQueue.cc
- src/PyBytesProxyHandler.cc
- src/PyDictProxyHandler.cc
- src/PyIterableProxyHandler.cc
- src/PyListProxyHandler.cc
- src/PyObjectProxyHandler.cc
- src/StrType.cc
- src/modules/pythonmonkey/pythonmonkey.cc
- src/setSpiderMonkeyException.cc
The CI sometimes [fail on `main`](https://github.com/Distributive-Network/PythonMonkey/actions/runs/11002881033/job/30550821137) even after we released the "stable" PythonMonkey v1.0.
After all pytests are done, the program segfaults during the Python interpreter finalization.
```console
============================= 678 passed in 23.59s =============================
/Users/runner/work/_temp/cab3e84e-a831-4a41-9c31-79102f1651a5.sh: line 7:  5781 Segmentation fault: 11  (core dumped) poetry run python -m pytest tests/python
```
---
Debugged using a debug build of Python
> Fix remaining memory bugs

- pyproject.toml
Update the PKG-INFO `pip show pythonmonkey` would give.
* Change the authors field to `Distributive Corp.`
* Add project description
* Add the MIT license
* Add links to our homepage and GitHub repo etc.
> Chore: update package information

- .github/workflows/test-and-publish.yaml
So that we don't have to maintain a Ubuntu VM inside of the office M1 mac mini. 
And forkers can run the CI by themselves.
> chore(CI): use GitHub-hosted runners for Linux arm64

- .github/workflows/test-and-publish.yaml
CI: Setup Python using pyenv to support building on older arm64 Ubuntu.
The `actions/setup-python` action only supports installing on arm64 Ubuntu 22.04
> CI: Build on Ubuntu 20.04 for arm64 linux release

- src/StrType.cc
SpiderMonkey doesn't store the extra null character while some Python APIs assume the string buffer is null-terminated.
The issue hasn't been a problem before because it somehow didn't allocate the buffer that follows, making the string buffer null-terminated effectively.
> fix the embedded null character issue
