Distributive-Network/PythonMonkey

- src/jsTypeFactory.cc
The total number of positional arguments for a Python function can be determined by the `co_argcount` field on the function's `PyCodeObject`. 
See:
https://docs.python.org/3.12/reference/datamodel.html?highlight=co_argcount
https://docs.python.org/3.11/c-api/code.html
https://github.com/python/cpython/blob/f3909b8/Include/cpython/code.h#L69
This patch eliminates expensive Python calls when using the Python `inspect` module.
> Perf: use `co_argcount` to determine number of arguments for a PyFunction

- src/modules/pythonmonkey/pythonmonkey.cc
- src/pyTypeFactory.cc
Python 3.8 broke again after few rounds of merges.
> Fix: GC of string on Python 3.8 

- tests/python/test_pythonmonkey_eval.py
https://github.com/Distributive-Network/PythonMonkey/actions/runs/5380926174/jobs/9764377201#step:9:38
> Properly fix tests of `eval_dates`

- .github/workflows/test-and-publish.yaml
- README.md
- setup.sh
`poetry-dynamic-versioning` needs to be installed as a Poetry plugin, otherwise Poetry will pickup the version value in `pyproject.toml` ([`version = "0"`](https://github.com/Distributive-Network/PythonMonkey/blob/43d610d/pyproject.toml#L3))
> Fix dynamic versioning

- README.md
- pyproject.toml
- python/pythonmonkey/require.py
Now we only have to run `poetry install` for development.
> Improve developer experience

- pmjs
- pmjs-lib/global-init.js
- python/pythonmonkey/builtin_modules/util.js
This patch causes pmjs to use util.inspect to display results
It also updates util.inspect to understand SpiderMonkey error objects
This PR entrains PR 73
> pmjs + util.inspect

- src/jsTypeFactory.cc
fixes https://github.com/Distributive-Network/PythonMonkey/issues/108
> Handle errors when populating the args to a Python function, otherwise it may segfault

- src/PromiseType.cc
fixes https://github.com/Distributive-Network/PythonMonkey/issues/107
> Fix `PythonAwaitable_Check`

- tests/js/js2py/function-curry.simple
- tests/js/js2py/higher-order-function.simple
- tests/js/js2py/trivial-function.simple
- tests/js/py2js/function-curry.simple.failing
- tests/js/py2js/higher-order-function.simple
- tests/js/py2js/trivial-function.simple
Adds various function tests for pmjs
> PMJS Tests: Functions

- src/jsTypeFactory.cc
- tests/python/test_pythonmonkey_eval.py
closes https://github.com/Distributive-Network/PythonMonkey/issues/84
> Handle nested exceptions in different languages

- .github/dependabot.yml
Adds dependabot capabilities to the project to enable dependabots automated weekly security updates and package updates.
> feat: Added dependabot yaml def for the npm libraries

- include/JSObjectProxy.hh
- src/JSObjectProxy.cc
- src/modules/pythonmonkey/pythonmonkey.cc
- tests/python/test_dicts_lists.py
Both in place and new object "|" op implemented
fixes #191
> JSObjectProxy now implements the dict "or" operation

- python/pminit/pythonmonkey/package-lock.json
This gets our packages up to date and upgrades us to a v3 lockfile. Tests all pass.
> Update JS deps

- .github/workflows/test-and-publish.yaml
closes https://github.com/Distributive-Network/PythonMonkey/issues/278
> HOTFIX: CI Broken on MacOS

- setup.sh
The [CI broke](https://github.com/Distributive-Network/PythonMonkey/actions/runs/8251094677/job/22574196946) for the same reason as https://github.com/Distributive-Network/PythonMonkey/pull/279.
Forgot to also make changes in `setup.sh`.
See https://github.com/Distributive-Network/PythonMonkey/pull/279
> HOTFIX: CI Broken on MacOS setup.sh

- README.md
> Update README to doc eval opts, pm.new, pm.valueOf, global symbols

- tests/js/eval-test.simple
Fixed a test to use platform independent paths
> Fix file eval on Windows

- include/PyDictProxyHandler.hh
- include/PyIterableProxyHandler.hh
- include/PyListProxyHandler.hh
- include/PyObjectProxyHandler.hh
- src/JSObjectProxy.cc
- src/PyDictProxyHandler.cc
- src/PyIterableProxyHandler.cc
- src/PyListProxyHandler.cc
- src/PyObjectProxyHandler.cc
- Improved documentation for PyXProxyHandler
- Improved variable naming
> Improved docs and naming

- src/PyIterableProxyHandler.cc
- tests/python/test_arrays.py
for-of loop now works with the iterable type as well
> Expand for-of loop support to iterable types

- include/PyIterableProxyHandler.hh
- src/PyIterableProxyHandler.cc
Refactor to avoid having duplicated common code
> Simplification of redundant patterns in iterable proxy

- python/pythonmonkey/builtin_modules/XMLHttpRequest-internal.py
- python/pythonmonkey/builtin_modules/XMLHttpRequest.js
- tests/js/xhr-http-keep-alive.bash
- tests/js/xhr.simple
closes https://github.com/Distributive-Network/PythonMonkey/issues/339
> Support HTTP-Keep-Alive in our `XMLHttpRequest` implementation

- include/JSStringProxy.hh
- include/StrType.hh
- src/JSStringProxy.cc
- src/StrType.cc
- src/modules/pythonmonkey/pythonmonkey.cc
- tests/python/test_strings.py
We were missing the implementation of the copy protocol for string proxies
closes https://github.com/Distributive-Network/PythonMonkey/issues/376
> Implement the copy protocol for string proxies

- setup.sh
quick fix to setup.sh to add cargo to PATH variable before using it
closes #373
> setup.sh cargo configuration

- src/JSObjectProxy.cc
> check if exception was set before clearing it

- README.md
Closes https://github.com/Distributive-Network/PythonMonkey/issues/430
> Docs: add uninstallation instructions in the README
